### ISSUE TITLE
The bubble sort is always unavoidably sorted one more time.

### ISSUE THREAD

**Issue by noseparte** [TheAlgorithms/Java#2052]
**Describe the bug**
The bubble sort is always unavoidably sorted one more time.

**To Reproduce**

please see **Screenshots**

**Expected behavior**
Can you improve the performance here?

**Screenshots**
- the test case
![image](https://user-images.githubusercontent.com/30165939/100427794-f3b3ae00-30cd-11eb-9c24-3b61133bbffa.png)
![image](https://user-images.githubusercontent.com/30165939/100428018-54db8180-30ce-11eb-857b-2a66118641f6.png)

**Device Specification**
windows10、Intellij IDEA、jdk8

**Additional context**

**Comment by brennanananan** [comment]
@noseparte By having your additional 
```java
System.out.println(Arrays.deepToString(array));
```
statement in the sort method, you are printing an additional time before the main method performs the print. I believe this is the reason you are seeing an additional step in the process, since this is printing one final time, assuming `swapped == false`, which is the case in the final step when no *bubbles* are occurring. Try removing the `print(integers);` statement from the driver and you will not see the the "repeated step".

**Comment by noseparte** [comment]
OK，you are right. @brennanananan
