### ISSUE TITLE
WildCard Pattern Matching- Dynamic Programming

### ISSUE THREAD

**Issue by nikitakapoor1919** [TheAlgorithms/Java#2419]
**Is your feature request related to a problem? Please describe.**
Given a text and wildcard pattern implement a wildcard pattern matching algorithm that finds if wildcard is matched with text. The matching should cover the entire text
?-> matches single characters
*-> match the sequence of characters

**Describe the solution you'd like**
I would like to implement this algorithm using three functions recursion, top-down DP, and bottom-up DP

**Describe alternatives you've considered**
After solving this algorithm we can analyze the time and space complexity of all methods.

Please assign me this task.
Thank you.

**Comment by ritweekraj2802** [comment]
Respected sir , please assign this problem to me.
Below is the algorithm ,code , output and time and space complexity

Given a text and a wildcard pattern, find if wildcard pattern is matched with text. The matching should cover the entire text (not partial text).
The wildcard pattern can include the characters ‘?’ and ‘*’:

‘?’ – matches any single character
‘*’ – Matches any sequence of characters (including the empty sequence)

Examples:

Text = "baaabab",
Pattern = “*****ba*****ab", output : true
Pattern = "baaa?ab", output : true
Pattern = "ba*a?", output : true
Pattern = "a*ab", output : false 


Algorithm:
Let i be the marker to point at the current character of the text. 
Let j be the marker to point at the current character of the pattern. 
Let index_txt be the marker to point at the character of text on which we encounter ‘*’ in the pattern. 
Let index_pat be the marker to point at the position of ‘*’ in the pattern.
At any instant, if we observe that txt[i] == pat[j], then we increment both i and j as no operation needs to be performed in this case.
If we encounter pat[j] == ‘?’, then it resembles the case mentioned in step – (2) as ‘?’ has the property to match with any single character.
If we encounter pat[j] == ‘*’, then we update the value of index_txt and index_pat as ‘*’ has the property to match any sequence of characters (including the empty sequence) and we will increment the value of j to compare next character of pattern with the current character of the text. (As character represented by i has not been answered yet).
Now if txt[i] == pat[j], and we have encountered a ‘*’ before, then it means that ‘*’ included the empty sequence, else if txt[i] != pat[j], a character needs to be provided by ‘*’ so that current character matching takes place, then i needs to be incremented as it is answered now but the character represented by j still needs to be answered, therefore, j = index_pat + 1, i = index_txt + 1 (as ‘*’ can capture other characters as well), index_txt++ (as current character in text is matched).
If step – (5) is not valid, that means txt[i] != pat[j], also we have not encountered a ‘*’ that means it is not possible for the pattern to match the string. (return false).
Check whether j reached its final value or not, then return the final answer.
code:

class WCPM {
 
    // Function that matches input text
    // with given wildcard pattern
    static boolean strmatch(char txt[], char pat[],
                            int n, int m)
    {
        // empty pattern can only
        // match with empty string.
        // Base Case :
        if (m == 0)
            return (n == 0);
 
        // step-1 :
        // initialize markers :
        int i = 0, j = 0, index_txt = -1,
            index_pat = -1;
 
        while (i < n)
        {
 
            // For step - (2, 5)
            if (j < m && txt[i] == pat[j])
            {
                i++;
                j++;
            }
 
            // For step - (3)
            else if (j < m && pat[j] == '?')
            {
                i++;
                j++;
            }
 
            // For step - (4)
            else if (j < m && pat[j] == '*')
            {
                index_txt = i;
                index_pat = j;
                j++;
            }
 
            // For step - (5)
            else if (index_pat != -1)
            {
                j = index_pat + 1;
                i = index_txt + 1;
                index_txt++;
            }
 
            // For step - (6)
            else
            {
                return false;
            }
        }
 
        // For step - (7)
        while (j < m && pat[j] == '*')
        {
            j++;
        }
 
        // Final Check
        if (j == m)
        {
            return true;
        }
 
        return false;
    }
 
    // Driver code
    public static void main(String[] args)
    {
         
        char str[] = "baaabab".toCharArray();
        char pattern[] = "*****ba*****ab".toCharArray();
        // char pattern[] = "ba*****ab";
        // char pattern[] = "ba*ab";
        // char pattern[] = "a*ab";
 
        if (strmatch(str, pattern, str.length,
                     pattern.length))
            System.out.println("Yes");
        else
            System.out.println("No");
 
        char pattern2[] = "a*****ab".toCharArray();
        if (strmatch(str, pattern2, str.length,
                     pattern2.length))
            System.out.println("Yes");
        else
            System.out.println("No");
    }
}

Output: 
Yes
No
 

Complexity Analysis: 

Time Complexity: O(m + n), where ‘m’ and ‘n’ are the lengths of text and pattern respectively.
Auxiliary Space: O(1). 
No use of any data structure for storing values

**Comment by nikitakapoor1919** [comment]
Hii @ritweekraj2802 
I have generated this issue so that I can make PR and I am waiting for the owner to assign me this task.
You can generate your new issue by referring to contributing guidelines.
Thankyou.

**Comment by nikitakapoor1919** [comment]
@siriak I have made a PR. Kindly Review
<a href="https://github.com/TheAlgorithms/Java/issues/2419">PR Link</a>
