### ISSUE TITLE
I think the method in SinglyLinkedList is not right implementation,

### ISSUE THREAD

**Issue by NewPZP** [TheAlgorithms/Java#2938]
I think the code following is not the right implementation,

https://github.com/TheAlgorithms/Java/blob/master/src/main/java/com/thealgorithms/datastructures/lists/SinglyLinkedList.java

/**
* Swaps nodes of two given values a and b.
*
*/
public void swapNodes(int a, int b) {
Node currentNode = head;
Node temp = null;
while (currentNode != null) {
if (currentNode.next.value == a) {
temp = currentNode.next;
}
if (currentNode.next.value == b) {
currentNode.next = temp;
}
currentNode = currentNode.next;
}
}

**Comment by zhrgithub** [comment]
really？

**Comment by zhrgithub** [comment]
Why are you think the code following is not the right implementation?

> 2022年2月9日 下午5:44，潘 ***@***.***> 写道：
> 
> I think the code following is not the right implementation,
> 
>

**Comment by YashCoder03** [comment]
Yes There is a Problem is swap funtion. They Change the values of Two Nodes Instead of **Nodes**. The Best Approch the Change the Nodes not values. Because In Real Time project if any node carring big amount of data then it is not good ot change values . it is better to change the Node.


If You assign this Task to Me Then i can Fix it..

**Comment by zhrgithub** [comment]
ok



---- 回复的原邮件 ----
| 发件人 | Yash ***@***.***> |
| 日期 | 2022年02月11日 01:44 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TheAlgorithms/Java] I think the method in SinglyLinkedList is not right implementation, (Issue #2938) |

Yes There is a Problem is swap funtion. They Change the values of Two Nodes Instead of Nodes. The Best Approch the Change the Nodes not values. Because In Real Time project if any node carring big amount of data then it is not good ot change values . it is better to change the Node.

If You assign this Task to Me Then i can Fix it..

**Comment by rajoriaakash** [comment]
Can i try on this issue?
