### ISSUE TITLE
[OTHER] Wrong assignment

### ISSUE THREAD

**Issue by lukasb1b** [TheAlgorithms/Java#4331]
### What would you like to share?

The files  src/main/java/com/thealgorithms/maths/FindMaxRecursion.java , src/main/java/com/thealgorithms/maths/FindMax.java , src/main/java/com/thealgorithms/maths/FindMin.java and src/main/java/com/thealgorithms/maths/FindMinRecursion.java are in the math folder. But they are searches so shouldn´t those be in the searches folder?

**Comment by azertl** [comment]
I understand that search algorithms are dedicated to the search of a specific pattern in a data set, eventually not finding it.
In that aspect, algorithms in the search package are search algorithms... well at least for those that I have opened before commenting your issue.
On the other side, the FindXXX algorithms are rather supposed to extract a specific information on the set of data that you have. It is simple math but in my opinion, it is still math, not search.
Furthermore, I like the fact that algorithms are categorized the same way in different languages. At least, in Python, they are also considered as search algorithms.

**Comment by siriak** [comment]
Thanks for bringing this up! I certainly see the problem here. Even in `searches` folder there are searches in a sorted array, in a graph, and other. It's not clear-cut how to organize them, and, as @azertl has already stated, there are also arguments in favor of having some of them in `maths`. Besides, they are all pulled in https://the-algorithms.com/ website, so moving them would break the website categorization.
