### ISSUE TITLE
CompareTo() method. 

### ISSUE THREAD

**Issue by lodedx** [TheAlgorithms/Java#5254]
### What would you like to share?

The library is missing Interface CompareTo() which is also called Comparable. 

### Additional information

Its a method to get 1,0 or -1 as return to determine the result.

**Comment by Parth-Dave18** [comment]
Hello @lodedx ,
sorry! but i did not get your idea what you want to say? I am a newbie, so please can you explain what you want to do? Because in my knowledge the Comparable Interface is inbuilt in java. so do you want anything different from that please explain.  I am eagerly waiting for you response.
thank you,
Parth Dave
