### ISSUE TITLE
javax.xml.bind.DatatypeConverter Java 11/12

### ISSUE THREAD

**Issue by RobertCoulter95** [TheAlgorithms/Java#792]
It seems that you can not import this is the newer versions of java. How can I get around this without using third party software?

**Comment by Balls-and-Dick-69** [comment]
link to code what are you talking about

**Comment by hakan0arslan** [comment]
He is talking about https://github.com/TheAlgorithms/Java/blob/master/ciphers/AESEncryption.java this class javax.xml.bind.DatatypeConverter is deprecated on OpenJdk 11. I made a pull request for this.  https://github.com/TheAlgorithms/Java/pull/1230 . This approach is faster because DataTypeConverter is using StringBuilder. More on that https://stackoverflow.com/questions/9655181/how-to-convert-a-byte-array-to-a-hex-string-in-java/9855338#9855338 .
