### ISSUE TITLE
Java\data_structures\Trees : Implementation of binary search tree methods in binary tree

### ISSUE THREAD

**Issue by mohit741** [TheAlgorithms/Java#89]
A <b>binary tree</b> is different from a <b>binary search tree</b>. Elements on left may not be always smaller so a clear <b>distinction</b> should be made.

**Comment by varunu28** [comment]
@dynamitechetan  I would like to work on this issue. I saw the implementation in the code and the issue seems to be correct. The binary tree actually implements the binary search tree. So it would have to be renamed and the explanation in the comments need to be improvised to make it more clear. Kindly assign this issue to me

**Comment by dynamitechetan** [comment]
Please work on this.
