### ISSUE TITLE
Which is preferred sorting algorithm 

### ISSUE THREAD

**Issue by mishraanmol** [TheAlgorithms/Java#92]
Suppose we are given a  set of values that are completely sorted, then among all the available sorting algorithms which one should we use?

For eg : 1,2,3,4,5,6,7,8,9

Query: What will be the time complexity of all the sorting algorithms in all the available cases.
Will selection and insertion sort will be suitable @varunu28 @AndrewJey @SergeyTsaplin @erugged93 @saurabhjn76

**Comment by varunu28** [comment]
You can use insertion sort with a flag to check if there  is a swap or not. It would do only one iteration i.e. O(n) 

In future kindly Google such queries rather than opening an issue in the repo as it is not an issue related to the code present in the repository
[Big-O Cheatsheet](http://bigocheatsheet.com/)

@AnupKumarPanwar  kindly close this
